services:
  docs:
    image: surfdjango_local_docs
    container_name: surfdjango_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/docs/config:z
      - ./surfdjango:/docs/surfdjango:z
    working_dir: /docs
    ports:
      - '9000:9000'
    command: /start-docs
