# Generated by Django 5.0.9 on 2024-10-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporation',
            old_name='adress',
            new_name='address',
        ),
    ]
